language: python

python:
  - "3.6"

postgres:
  adapter: postgresql
  database: recipedb
  username: postgres

before_script:
  - "psql -c 'create database recipedb;' -U postgres"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - cd app
  - python manage.py test && flake8